Config.Recipes = {

    ['m4a9_nike'] = {
        label = 'M4A9 - Nike Edition',
        description = 'Custom M4A9 carbine rifle with Nike-inspired aesthetic finish.',
        image = 'weapons/weapon_carbinerifle.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 900,
        minLevel = 0,
        ingredients = {
            { item = 'steel',      count = 6, label = 'Steel',      image = 'materials/steel.png' },
            { item = 'metalscrap', count = 8, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 4, label = 'Plastic',    image = 'materials/plastic.png' },
            { item = 'aluminum',   count = 3, label = 'Aluminium',  image = 'materials/aluminum.png' },
        },
        result = { item = 'weapon_carbinerifle', count = 1, ammo = 0 },
    },

    ['ak47_custom'] = {
        label = 'AK-47 Custom',
        description = 'A customized AK-47 assault rifle built from salvaged parts.',
        image = 'weapons/weapon_assaultrifle.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 480,
        minLevel = 3,
        ingredients = {
            { item = 'steel',      count = 5, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 7, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'rubber',     count = 2, label = 'Rubber',      image = 'materials/rubber.png' },
            { item = 'copper',     count = 2, label = 'Copper',      image = 'materials/copper.png' },
        },
        result = { item = 'weapon_assaultrifle', count = 1, ammo = 0 },
    },

    ['pistol_mk2'] = {
        label = 'Pistol MK2',
        description = 'Upgraded pistol with improved accuracy and damage.',
        image = 'weapons/weapon_pistol_mk2.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 300,
        minLevel = 1,
        ingredients = {
            { item = 'iron',       count = 3, label = 'Iron',        image = 'materials/iron.png' },
            { item = 'metalscrap', count = 4, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 2, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'weapon_pistol_mk2', count = 1, ammo = 0 },
    },

    ['combat_pdw'] = {
        label = 'Combat PDW',
        description = 'Compact personal defense weapon for close encounters.',
        image = 'weapons/weapon_combatpdw.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 420,
        minLevel = 5,
        ingredients = {
            { item = 'steel',      count = 4, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 5, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 3, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'copper',     count = 2, label = 'Copper',      image = 'materials/copper.png' },
        },
        result = { item = 'weapon_combatpdw', count = 1, ammo = 0 },
    },

    ['ap_pistol'] = {
        label = 'AP Pistol',
        description = 'Armor-piercing pistol favored by street enforcers.',
        image = 'weapons/weapon_appistol.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 360,
        minLevel = 2,
        ingredients = {
            { item = 'iron',       count = 3, label = 'Iron',        image = 'materials/iron.png' },
            { item = 'metalscrap', count = 5, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 2, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'weapon_appistol', count = 1, ammo = 0 },
    },

    ['micro_smg'] = {
        label = 'Micro SMG',
        description = 'Ultra-compact submachine gun, easy to conceal.',
        image = 'weapons/weapon_microsmg.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 420,
        minLevel = 4,
        ingredients = {
            { item = 'steel',      count = 3, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 5, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 3, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'weapon_microsmg', count = 1, ammo = 0 },
    },

    ['pump_shotgun'] = {
        label = 'Pump Shotgun',
        description = 'Reliable pump-action shotgun with brutal close-range power.',
        image = 'weapons/weapon_pumpshotgun.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 540,
        minLevel = 4,
        ingredients = {
            { item = 'steel',      count = 4, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 6, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'rubber',     count = 2, label = 'Rubber',      image = 'materials/rubber.png' },
        },
        result = { item = 'weapon_pumpshotgun', count = 1, ammo = 0 },
    },

    ['sawnoff_shotgun'] = {
        label = 'Sawn-Off Shotgun',
        description = 'Shortened barrel for raw close-range damage.',
        image = 'weapons/weapon_sawnoffshotgun.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 360,
        minLevel = 2,
        ingredients = {
            { item = 'iron',       count = 3, label = 'Iron',        image = 'materials/iron.png' },
            { item = 'metalscrap', count = 4, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'rubber',     count = 1, label = 'Rubber',      image = 'materials/rubber.png' },
        },
        result = { item = 'weapon_sawnoffshotgun', count = 1, ammo = 0 },
    },

    ['smg_mk2'] = {
        label = 'SMG MK2',
        description = 'Upgraded submachine gun with improved recoil control.',
        image = 'weapons/weapon_smg_mk2.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 600,
        minLevel = 6,
        ingredients = {
            { item = 'steel',      count = 4, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 6, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 3, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'copper',     count = 3, label = 'Copper',      image = 'materials/copper.png' },
        },
        result = { item = 'weapon_smg_mk2', count = 1, ammo = 0 },
    },

    ['marksman_rifle'] = {
        label = 'Marksman Rifle',
        description = 'Precision mid-range rifle with a tactical scope.',
        image = 'weapons/weapon_marksmanrifle.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 720,
        minLevel = 7,
        ingredients = {
            { item = 'steel',      count = 6, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 8, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 3, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'glass',      count = 2, label = 'Glass',       image = 'materials/glass.png' },
            { item = 'copper',     count = 2, label = 'Copper',      image = 'materials/copper.png' },
        },
        result = { item = 'weapon_marksmanrifle', count = 1, ammo = 0 },
    },

    ['sniper_rifle'] = {
        label = 'Sniper Rifle',
        description = 'Long-range precision weapon for skilled operators.',
        image = 'weapons/weapon_sniperrifle.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 900,
        minLevel = 9,
        ingredients = {
            { item = 'steel',      count = 8, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 10, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 4, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'glass',      count = 3, label = 'Glass',       image = 'materials/glass.png' },
            { item = 'copper',     count = 3, label = 'Copper',      image = 'materials/copper.png' },
        },
        result = { item = 'weapon_sniperrifle', count = 1, ammo = 0 },
    },

    ['heavy_pistol'] = {
        label = 'Heavy Pistol',
        description = 'Oversized pistol packing serious stopping power.',
        image = 'weapons/weapon_heavypistol.png',
        category = 'weapon',
        resultType = 'weapon',
        craftTime = 360,
        minLevel = 3,
        ingredients = {
            { item = 'iron',       count = 4, label = 'Iron',        image = 'materials/iron.png' },
            { item = 'metalscrap', count = 5, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 2, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'copper',     count = 1, label = 'Copper',      image = 'materials/copper.png' },
        },
        result = { item = 'weapon_heavypistol', count = 1, ammo = 0 },
    },


    -- AMMUNITION
    ['ammo_9'] = {
        label = '9mm Ammunition',
        description = 'Box of 9mm ammunition.',
        image = 'ammo/ammo-9.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 60,
        minLevel = 1,
        ingredients = {
            { item = 'copper',     count = 2, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 1, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 2, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 1, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'ammo-9', count = 24 },
    },

    ['ammo_45'] = {
        label = '.45 ACP Ammunition',
        description = 'Box of .45 ACP ammunition.',
        image = 'ammo/ammo-45.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 75,
        minLevel = 2,
        ingredients = {
            { item = 'copper',     count = 3, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 2, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 2, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 1, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'ammo-45', count = 24 },
    },

    ['ammo_50'] = {
        label = '.50 AE Ammunition',
        description = 'Box of .50 AE ammunition.',
        image = 'ammo/ammo-50.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 90,
        minLevel = 3,
        ingredients = {
            { item = 'copper',     count = 4, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 3, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 3, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 1, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'ammo-50', count = 20 },
    },

    ['ammo_38'] = {
        label = '.38 LC Ammunition',
        description = 'Box of .38 ammunition.',
        image = 'ammo/ammo-38.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 60,
        minLevel = 1,
        ingredients = {
            { item = 'copper',     count = 2, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 1, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 2, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
        },
        result = { item = 'ammo-38', count = 24 },
    },

    ['ammo_44'] = {
        label = '.44 Magnum Ammunition',
        description = 'Box of .44 Magnum ammunition.',
        image = 'ammo/ammo-44.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 75,
        minLevel = 2,
        ingredients = {
            { item = 'copper',     count = 3, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 2, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 3, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
        },
        result = { item = 'ammo-44', count = 24 },
    },

    ['ammo_22'] = {
        label = '.22 LR Ammunition',
        description = 'Box of .22 ammunition.',
        image = 'ammo/ammo-22.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 45,
        minLevel = 0,
        ingredients = {
            { item = 'copper',     count = 1, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 1, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 1, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
        },
        result = { item = 'ammo-22', count = 30 },
    },

    ['ammo_rifle'] = {
        label = '5.56x45 Ammunition',
        description = 'Box of 5.56x45 rifle ammunition.',
        image = 'ammo/ammo-rifle.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 90,
        minLevel = 3,
        ingredients = {
            { item = 'copper',     count = 4, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 3, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 4, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 2, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'ammo-rifle', count = 30 },
    },

    ['ammo_rifle2'] = {
        label = '7.62x39 Ammunition',
        description = 'Box of 7.62x39 rifle ammunition.',
        image = 'ammo/ammo-rifle2.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 105,
        minLevel = 4,
        ingredients = {
            { item = 'copper',     count = 5, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 4, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 5, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 2, label = 'Plastic',     image = 'materials/plastic.png' },
        },
        result = { item = 'ammo-rifle2', count = 30 },
    },

    ['ammo_shotgun'] = {
        label = '12 Gauge Ammunition',
        description = 'Box of 12 gauge shotgun shells.',
        image = 'ammo/ammo-shotgun.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 90,
        minLevel = 2,
        ingredients = {
            { item = 'copper',     count = 4, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'plastic',    count = 3, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'steel',      count = 2, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 3, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
        },
        result = { item = 'ammo-shotgun', count = 20 },
    },

    ['ammo_sniper'] = {
        label = '7.62x51 Ammunition',
        description = 'Box of 7.62x51 sniper ammunition.',
        image = 'ammo/ammo-sniper.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 120,
        minLevel = 6,
        ingredients = {
            { item = 'copper',     count = 5, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 5, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 6, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 2, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'glass',      count = 1, label = 'Glass',       image = 'materials/glass.png' },
        },
        result = { item = 'ammo-sniper', count = 20 },
    },

    ['ammo_heavysniper'] = {
        label = '.50 BMG Ammunition',
        description = 'Box of .50 BMG ammunition.',
        image = 'ammo/ammo-heavysniper.png',
        category = 'ammo',
        resultType = 'item',
        craftTime = 150,
        minLevel = 8,
        ingredients = {
            { item = 'copper',     count = 6, label = 'Copper',      image = 'materials/copper.png' },
            { item = 'steel',      count = 6, label = 'Steel',       image = 'materials/steel.png' },
            { item = 'metalscrap', count = 7, label = 'Metal Scrap', image = 'materials/metalscrap.png' },
            { item = 'plastic',    count = 3, label = 'Plastic',     image = 'materials/plastic.png' },
            { item = 'glass',      count = 1, label = 'Glass',       image = 'materials/glass.png' },
        },
        result = { item = 'ammo-heavysniper', count = 15 },
    },
}
